//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadanie2_klient.zad2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="zad2.zadanie2Soap")]
    public interface zadanie2Soap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu id1 z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WypiszMacierz", ReplyAction="*")]
        zadanie2_klient.zad2.WypiszMacierzResponse WypiszMacierz(zadanie2_klient.zad2.WypiszMacierzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WypiszMacierz", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.WypiszMacierzResponse> WypiszMacierzAsync(zadanie2_klient.zad2.WypiszMacierzRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WypiszMacierzRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WypiszMacierz", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.WypiszMacierzRequestBody Body;
        
        public WypiszMacierzRequest() {
        }
        
        public WypiszMacierzRequest(zadanie2_klient.zad2.WypiszMacierzRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WypiszMacierzRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id2;
        
        public WypiszMacierzRequestBody() {
        }
        
        public WypiszMacierzRequestBody(string id1, string id2) {
            this.id1 = id1;
            this.id2 = id2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WypiszMacierzResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WypiszMacierzResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.WypiszMacierzResponseBody Body;
        
        public WypiszMacierzResponse() {
        }
        
        public WypiszMacierzResponse(zadanie2_klient.zad2.WypiszMacierzResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WypiszMacierzResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WypiszMacierzResult;
        
        public WypiszMacierzResponseBody() {
        }
        
        public WypiszMacierzResponseBody(string WypiszMacierzResult) {
            this.WypiszMacierzResult = WypiszMacierzResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zadanie2SoapChannel : zadanie2_klient.zad2.zadanie2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zadanie2SoapClient : System.ServiceModel.ClientBase<zadanie2_klient.zad2.zadanie2Soap>, zadanie2_klient.zad2.zadanie2Soap {
        
        public zadanie2SoapClient() {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zadanie2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.WypiszMacierzResponse zadanie2_klient.zad2.zadanie2Soap.WypiszMacierz(zadanie2_klient.zad2.WypiszMacierzRequest request) {
            return base.Channel.WypiszMacierz(request);
        }
        
        public string WypiszMacierz(string id1, string id2) {
            zadanie2_klient.zad2.WypiszMacierzRequest inValue = new zadanie2_klient.zad2.WypiszMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.WypiszMacierzRequestBody();
            inValue.Body.id1 = id1;
            inValue.Body.id2 = id2;
            zadanie2_klient.zad2.WypiszMacierzResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).WypiszMacierz(inValue);
            return retVal.Body.WypiszMacierzResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.WypiszMacierzResponse> zadanie2_klient.zad2.zadanie2Soap.WypiszMacierzAsync(zadanie2_klient.zad2.WypiszMacierzRequest request) {
            return base.Channel.WypiszMacierzAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.WypiszMacierzResponse> WypiszMacierzAsync(string id1, string id2) {
            zadanie2_klient.zad2.WypiszMacierzRequest inValue = new zadanie2_klient.zad2.WypiszMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.WypiszMacierzRequestBody();
            inValue.Body.id1 = id1;
            inValue.Body.id2 = id2;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).WypiszMacierzAsync(inValue);
        }
    }
}
