//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadanie2_klient.zad2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="zad2.zadanie2Soap")]
    public interface zadanie2Soap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu id1 z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrzemnozMacierz", ReplyAction="*")]
        zadanie2_klient.zad2.PrzemnozMacierzResponse PrzemnozMacierz(zadanie2_klient.zad2.PrzemnozMacierzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrzemnozMacierz", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.PrzemnozMacierzResponse> PrzemnozMacierzAsync(zadanie2_klient.zad2.PrzemnozMacierzRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu id z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzMacierz", ReplyAction="*")]
        zadanie2_klient.zad2.PobierzMacierzResponse PobierzMacierz(zadanie2_klient.zad2.PobierzMacierzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzMacierz", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.PobierzMacierzResponse> PobierzMacierzAsync(zadanie2_klient.zad2.PobierzMacierzRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu DrawMandelResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrawMandel", ReplyAction="*")]
        zadanie2_klient.zad2.DrawMandelResponse DrawMandel(zadanie2_klient.zad2.DrawMandelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrawMandel", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.DrawMandelResponse> DrawMandelAsync(zadanie2_klient.zad2.DrawMandelRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu b64 z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapiszPlik", ReplyAction="*")]
        zadanie2_klient.zad2.ZapiszPlikResponse ZapiszPlik(zadanie2_klient.zad2.ZapiszPlikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapiszPlik", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.ZapiszPlikResponse> ZapiszPlikAsync(zadanie2_klient.zad2.ZapiszPlikRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrzemnozMacierzRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrzemnozMacierz", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.PrzemnozMacierzRequestBody Body;
        
        public PrzemnozMacierzRequest() {
        }
        
        public PrzemnozMacierzRequest(zadanie2_klient.zad2.PrzemnozMacierzRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrzemnozMacierzRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id2;
        
        public PrzemnozMacierzRequestBody() {
        }
        
        public PrzemnozMacierzRequestBody(string id1, string id2) {
            this.id1 = id1;
            this.id2 = id2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrzemnozMacierzResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrzemnozMacierzResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.PrzemnozMacierzResponseBody Body;
        
        public PrzemnozMacierzResponse() {
        }
        
        public PrzemnozMacierzResponse(zadanie2_klient.zad2.PrzemnozMacierzResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrzemnozMacierzResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrzemnozMacierzResult;
        
        public PrzemnozMacierzResponseBody() {
        }
        
        public PrzemnozMacierzResponseBody(string PrzemnozMacierzResult) {
            this.PrzemnozMacierzResult = PrzemnozMacierzResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzMacierzRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzMacierz", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.PobierzMacierzRequestBody Body;
        
        public PobierzMacierzRequest() {
        }
        
        public PobierzMacierzRequest(zadanie2_klient.zad2.PobierzMacierzRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzMacierzRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public PobierzMacierzRequestBody() {
        }
        
        public PobierzMacierzRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzMacierzResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzMacierzResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.PobierzMacierzResponseBody Body;
        
        public PobierzMacierzResponse() {
        }
        
        public PobierzMacierzResponse(zadanie2_klient.zad2.PobierzMacierzResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzMacierzResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PobierzMacierzResult;
        
        public PobierzMacierzResponseBody() {
        }
        
        public PobierzMacierzResponseBody(string PobierzMacierzResult) {
            this.PobierzMacierzResult = PobierzMacierzResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DrawMandelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DrawMandel", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.DrawMandelRequestBody Body;
        
        public DrawMandelRequest() {
        }
        
        public DrawMandelRequest(zadanie2_klient.zad2.DrawMandelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DrawMandelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Sx;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double Sy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double Fx;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double Fy;
        
        public DrawMandelRequestBody() {
        }
        
        public DrawMandelRequestBody(int width, int height, double Sx, double Sy, double Fx, double Fy) {
            this.width = width;
            this.height = height;
            this.Sx = Sx;
            this.Sy = Sy;
            this.Fx = Fx;
            this.Fy = Fy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DrawMandelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DrawMandelResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.DrawMandelResponseBody Body;
        
        public DrawMandelResponse() {
        }
        
        public DrawMandelResponse(zadanie2_klient.zad2.DrawMandelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DrawMandelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DrawMandelResult;
        
        public DrawMandelResponseBody() {
        }
        
        public DrawMandelResponseBody(string DrawMandelResult) {
            this.DrawMandelResult = DrawMandelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZapiszPlikRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZapiszPlik", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.ZapiszPlikRequestBody Body;
        
        public ZapiszPlikRequest() {
        }
        
        public ZapiszPlikRequest(zadanie2_klient.zad2.ZapiszPlikRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZapiszPlikRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string b64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public ZapiszPlikRequestBody() {
        }
        
        public ZapiszPlikRequestBody(string b64, string id) {
            this.b64 = b64;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZapiszPlikResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZapiszPlikResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.ZapiszPlikResponseBody Body;
        
        public ZapiszPlikResponse() {
        }
        
        public ZapiszPlikResponse(zadanie2_klient.zad2.ZapiszPlikResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZapiszPlikResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZapiszPlikResult;
        
        public ZapiszPlikResponseBody() {
        }
        
        public ZapiszPlikResponseBody(string ZapiszPlikResult) {
            this.ZapiszPlikResult = ZapiszPlikResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zadanie2SoapChannel : zadanie2_klient.zad2.zadanie2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zadanie2SoapClient : System.ServiceModel.ClientBase<zadanie2_klient.zad2.zadanie2Soap>, zadanie2_klient.zad2.zadanie2Soap {
        
        public zadanie2SoapClient() {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zadanie2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.PrzemnozMacierzResponse zadanie2_klient.zad2.zadanie2Soap.PrzemnozMacierz(zadanie2_klient.zad2.PrzemnozMacierzRequest request) {
            return base.Channel.PrzemnozMacierz(request);
        }
        
        public string PrzemnozMacierz(string id1, string id2) {
            zadanie2_klient.zad2.PrzemnozMacierzRequest inValue = new zadanie2_klient.zad2.PrzemnozMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.PrzemnozMacierzRequestBody();
            inValue.Body.id1 = id1;
            inValue.Body.id2 = id2;
            zadanie2_klient.zad2.PrzemnozMacierzResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).PrzemnozMacierz(inValue);
            return retVal.Body.PrzemnozMacierzResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.PrzemnozMacierzResponse> zadanie2_klient.zad2.zadanie2Soap.PrzemnozMacierzAsync(zadanie2_klient.zad2.PrzemnozMacierzRequest request) {
            return base.Channel.PrzemnozMacierzAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.PrzemnozMacierzResponse> PrzemnozMacierzAsync(string id1, string id2) {
            zadanie2_klient.zad2.PrzemnozMacierzRequest inValue = new zadanie2_klient.zad2.PrzemnozMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.PrzemnozMacierzRequestBody();
            inValue.Body.id1 = id1;
            inValue.Body.id2 = id2;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).PrzemnozMacierzAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.PobierzMacierzResponse zadanie2_klient.zad2.zadanie2Soap.PobierzMacierz(zadanie2_klient.zad2.PobierzMacierzRequest request) {
            return base.Channel.PobierzMacierz(request);
        }
        
        public string PobierzMacierz(string id) {
            zadanie2_klient.zad2.PobierzMacierzRequest inValue = new zadanie2_klient.zad2.PobierzMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.PobierzMacierzRequestBody();
            inValue.Body.id = id;
            zadanie2_klient.zad2.PobierzMacierzResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).PobierzMacierz(inValue);
            return retVal.Body.PobierzMacierzResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.PobierzMacierzResponse> zadanie2_klient.zad2.zadanie2Soap.PobierzMacierzAsync(zadanie2_klient.zad2.PobierzMacierzRequest request) {
            return base.Channel.PobierzMacierzAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.PobierzMacierzResponse> PobierzMacierzAsync(string id) {
            zadanie2_klient.zad2.PobierzMacierzRequest inValue = new zadanie2_klient.zad2.PobierzMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.PobierzMacierzRequestBody();
            inValue.Body.id = id;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).PobierzMacierzAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.DrawMandelResponse zadanie2_klient.zad2.zadanie2Soap.DrawMandel(zadanie2_klient.zad2.DrawMandelRequest request) {
            return base.Channel.DrawMandel(request);
        }
        
        public string DrawMandel(int width, int height, double Sx, double Sy, double Fx, double Fy) {
            zadanie2_klient.zad2.DrawMandelRequest inValue = new zadanie2_klient.zad2.DrawMandelRequest();
            inValue.Body = new zadanie2_klient.zad2.DrawMandelRequestBody();
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.Sx = Sx;
            inValue.Body.Sy = Sy;
            inValue.Body.Fx = Fx;
            inValue.Body.Fy = Fy;
            zadanie2_klient.zad2.DrawMandelResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).DrawMandel(inValue);
            return retVal.Body.DrawMandelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.DrawMandelResponse> zadanie2_klient.zad2.zadanie2Soap.DrawMandelAsync(zadanie2_klient.zad2.DrawMandelRequest request) {
            return base.Channel.DrawMandelAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.DrawMandelResponse> DrawMandelAsync(int width, int height, double Sx, double Sy, double Fx, double Fy) {
            zadanie2_klient.zad2.DrawMandelRequest inValue = new zadanie2_klient.zad2.DrawMandelRequest();
            inValue.Body = new zadanie2_klient.zad2.DrawMandelRequestBody();
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.Sx = Sx;
            inValue.Body.Sy = Sy;
            inValue.Body.Fx = Fx;
            inValue.Body.Fy = Fy;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).DrawMandelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.ZapiszPlikResponse zadanie2_klient.zad2.zadanie2Soap.ZapiszPlik(zadanie2_klient.zad2.ZapiszPlikRequest request) {
            return base.Channel.ZapiszPlik(request);
        }
        
        public string ZapiszPlik(string b64, string id) {
            zadanie2_klient.zad2.ZapiszPlikRequest inValue = new zadanie2_klient.zad2.ZapiszPlikRequest();
            inValue.Body = new zadanie2_klient.zad2.ZapiszPlikRequestBody();
            inValue.Body.b64 = b64;
            inValue.Body.id = id;
            zadanie2_klient.zad2.ZapiszPlikResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).ZapiszPlik(inValue);
            return retVal.Body.ZapiszPlikResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.ZapiszPlikResponse> zadanie2_klient.zad2.zadanie2Soap.ZapiszPlikAsync(zadanie2_klient.zad2.ZapiszPlikRequest request) {
            return base.Channel.ZapiszPlikAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.ZapiszPlikResponse> ZapiszPlikAsync(string b64, string id) {
            zadanie2_klient.zad2.ZapiszPlikRequest inValue = new zadanie2_klient.zad2.ZapiszPlikRequest();
            inValue.Body = new zadanie2_klient.zad2.ZapiszPlikRequestBody();
            inValue.Body.b64 = b64;
            inValue.Body.id = id;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).ZapiszPlikAsync(inValue);
        }
    }
}
