//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zadanie2_klient.zad2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="zad2.zadanie2Soap")]
    public interface zadanie2Soap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu id1 z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WypiszMacierz", ReplyAction="*")]
        zadanie2_klient.zad2.WypiszMacierzResponse WypiszMacierz(zadanie2_klient.zad2.WypiszMacierzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WypiszMacierz", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.WypiszMacierzResponse> WypiszMacierzAsync(zadanie2_klient.zad2.WypiszMacierzRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu DrawMandelResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrawMandel", ReplyAction="*")]
        zadanie2_klient.zad2.DrawMandelResponse DrawMandel(zadanie2_klient.zad2.DrawMandelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DrawMandel", ReplyAction="*")]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.DrawMandelResponse> DrawMandelAsync(zadanie2_klient.zad2.DrawMandelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WypiszMacierzRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WypiszMacierz", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.WypiszMacierzRequestBody Body;
        
        public WypiszMacierzRequest() {
        }
        
        public WypiszMacierzRequest(zadanie2_klient.zad2.WypiszMacierzRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WypiszMacierzRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id2;
        
        public WypiszMacierzRequestBody() {
        }
        
        public WypiszMacierzRequestBody(string id1, string id2) {
            this.id1 = id1;
            this.id2 = id2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WypiszMacierzResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WypiszMacierzResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.WypiszMacierzResponseBody Body;
        
        public WypiszMacierzResponse() {
        }
        
        public WypiszMacierzResponse(zadanie2_klient.zad2.WypiszMacierzResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WypiszMacierzResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WypiszMacierzResult;
        
        public WypiszMacierzResponseBody() {
        }
        
        public WypiszMacierzResponseBody(string WypiszMacierzResult) {
            this.WypiszMacierzResult = WypiszMacierzResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DrawMandelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DrawMandel", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.DrawMandelRequestBody Body;
        
        public DrawMandelRequest() {
        }
        
        public DrawMandelRequest(zadanie2_klient.zad2.DrawMandelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DrawMandelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Sx;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double Sy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double Fx;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double Fy;
        
        public DrawMandelRequestBody() {
        }
        
        public DrawMandelRequestBody(int width, int height, double Sx, double Sy, double Fx, double Fy) {
            this.width = width;
            this.height = height;
            this.Sx = Sx;
            this.Sy = Sy;
            this.Fx = Fx;
            this.Fy = Fy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DrawMandelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DrawMandelResponse", Namespace="http://tempuri.org/", Order=0)]
        public zadanie2_klient.zad2.DrawMandelResponseBody Body;
        
        public DrawMandelResponse() {
        }
        
        public DrawMandelResponse(zadanie2_klient.zad2.DrawMandelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DrawMandelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DrawMandelResult;
        
        public DrawMandelResponseBody() {
        }
        
        public DrawMandelResponseBody(string DrawMandelResult) {
            this.DrawMandelResult = DrawMandelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zadanie2SoapChannel : zadanie2_klient.zad2.zadanie2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zadanie2SoapClient : System.ServiceModel.ClientBase<zadanie2_klient.zad2.zadanie2Soap>, zadanie2_klient.zad2.zadanie2Soap {
        
        public zadanie2SoapClient() {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zadanie2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zadanie2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.WypiszMacierzResponse zadanie2_klient.zad2.zadanie2Soap.WypiszMacierz(zadanie2_klient.zad2.WypiszMacierzRequest request) {
            return base.Channel.WypiszMacierz(request);
        }
        
        public string WypiszMacierz(string id1, string id2) {
            zadanie2_klient.zad2.WypiszMacierzRequest inValue = new zadanie2_klient.zad2.WypiszMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.WypiszMacierzRequestBody();
            inValue.Body.id1 = id1;
            inValue.Body.id2 = id2;
            zadanie2_klient.zad2.WypiszMacierzResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).WypiszMacierz(inValue);
            return retVal.Body.WypiszMacierzResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.WypiszMacierzResponse> zadanie2_klient.zad2.zadanie2Soap.WypiszMacierzAsync(zadanie2_klient.zad2.WypiszMacierzRequest request) {
            return base.Channel.WypiszMacierzAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.WypiszMacierzResponse> WypiszMacierzAsync(string id1, string id2) {
            zadanie2_klient.zad2.WypiszMacierzRequest inValue = new zadanie2_klient.zad2.WypiszMacierzRequest();
            inValue.Body = new zadanie2_klient.zad2.WypiszMacierzRequestBody();
            inValue.Body.id1 = id1;
            inValue.Body.id2 = id2;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).WypiszMacierzAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zadanie2_klient.zad2.DrawMandelResponse zadanie2_klient.zad2.zadanie2Soap.DrawMandel(zadanie2_klient.zad2.DrawMandelRequest request) {
            return base.Channel.DrawMandel(request);
        }
        
        public string DrawMandel(int width, int height, double Sx, double Sy, double Fx, double Fy) {
            zadanie2_klient.zad2.DrawMandelRequest inValue = new zadanie2_klient.zad2.DrawMandelRequest();
            inValue.Body = new zadanie2_klient.zad2.DrawMandelRequestBody();
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.Sx = Sx;
            inValue.Body.Sy = Sy;
            inValue.Body.Fx = Fx;
            inValue.Body.Fy = Fy;
            zadanie2_klient.zad2.DrawMandelResponse retVal = ((zadanie2_klient.zad2.zadanie2Soap)(this)).DrawMandel(inValue);
            return retVal.Body.DrawMandelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<zadanie2_klient.zad2.DrawMandelResponse> zadanie2_klient.zad2.zadanie2Soap.DrawMandelAsync(zadanie2_klient.zad2.DrawMandelRequest request) {
            return base.Channel.DrawMandelAsync(request);
        }
        
        public System.Threading.Tasks.Task<zadanie2_klient.zad2.DrawMandelResponse> DrawMandelAsync(int width, int height, double Sx, double Sy, double Fx, double Fy) {
            zadanie2_klient.zad2.DrawMandelRequest inValue = new zadanie2_klient.zad2.DrawMandelRequest();
            inValue.Body = new zadanie2_klient.zad2.DrawMandelRequestBody();
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.Sx = Sx;
            inValue.Body.Sy = Sy;
            inValue.Body.Fx = Fx;
            inValue.Body.Fy = Fy;
            return ((zadanie2_klient.zad2.zadanie2Soap)(this)).DrawMandelAsync(inValue);
        }
    }
}
